### ISSUE TITLE
Label file for CCF v3 2017

### ISSUE THREAD

**Issue by ingvildeb** [Neural-Systems-at-UIO/Atlas-support#5]
Hi,

I am trying to open the 2017 version of the CCF in ITK-snap. I am using the template and segmentation files found here: Z:\HBP_Atlasing\ATLAS_AMBA-mouse_templates\v3_2017_full_10um

However, when I try loading the labels (I tried the one found here, Z:\HBP_Analytics\Nutil\Nutil_releases\Label_files) it gives me an error message (see attachment)

Can anyone help me solve this or point me to a label file for v3 2017 that would work in ITK? Preferably one that includes all regions such as the one used in Nutil Quantifier.

@Tevemadar 

![Skjermbilde2](https://user-images.githubusercontent.com/28010291/79105712-7bcc8980-7d71-11ea-98e4-a380cbaafdb4.PNG)

**Comment by Tevemadar** [comment]
ITK Snap does not support label identifiers starting with 65536 and above (it may look like a strange number, but it is a very "round" one for computers: 10000h in hexadecimal. The point is that just as in decimal, 10000 is the first 5-digit number, and ITK supports 4-digit label identifiers only).
AMBA uses all kind of large numbers, like the 10th label, `526157192	38	143	69	1	1	1	"Frontal pole, layer 5"`. These can be commented (by putting a `#` in front of the line) or removed and then ITK Snap will open the label descriptors.
It is important to note that ITK Snap "makes" the volume itself 4-digit too, by simply throwing away the upper digits which may lead to collisions (like if you have a number, 12340001 and keep only the 0001 from it, that will appear being 1 afterwards, displaying whatever name and color which was assigned to that label).
This is why we have some reduced/renumbered volumes, like the one in HBP_Atlasing\ATLAS_AMBA-mouse_templates\v3_red_216_2017, just at this moment I do not know what it really contains.

**Comment by ingvildeb** [comment]
OK, thanks for clarifying!
